manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ebastler
      url-base: https://github.com/ebastler
  projects:
    - name: zmk
      remote: ebastler
      revision: testbranch
      import: app/west.yml
  self:
    path: config
